### ISSUE TITLE
How to hook up Instance class constructor to object created in gamemaker editor?

### ISSUE THREAD

**Issue by amiani** [YellowAfterlife/sfgml#4]
Hello Vadim,
Is there a way to call the constructor of an Instance subclass when an object is instantiated using the gamemaker editor i.e. dragged into a room?

Also, is there an intended way to listen to Object events in Haxe?

**Comment by YellowAfterlife** [comment]
Hello,

The easiest way around would be to give the class a child class with a dummy constructor, which would cause the generator to split the parent's constructor into `_create`+`_new` (and you'd call the later).

Currently you would just give your class accordingly named methods and call them from GML side. I have been experimenting with updating GMS2 objects based on Haxe class layout and was going to respond once that is done, but there's actually a lot going on right now.
