### ISSUE TITLE
Support for enclosures

### ISSUE THREAD

**Issue by XANOZOID** [YellowAfterlife/sfgml#7]
Hello, are there currently any plans to support enclosures? From the looks of it, there's a compiler error when trying to store a reference to an instance's method inside of a variable. 

It's a critical feature used in several haxe libraries and all over the language and I was surprised my friend Ian, creator of  haxeui, ran into it... 

The code he tested was: 

 ```haxe

    private var _testFn:Void->Void;
    
    public function new() {
        _testFn = myTestFn;
    }
    
    private function myTestFn() {
    }
```
 
And it ran into a compiler error saying:

`src/haxe/ui/Component.hx:17: characters 19-27 : Can't print SfClosureField` 

Any help or word is greatly appreciated!

**Comment by ianharrigan** [comment]
Its also worth pointing out that you can "fix" the issue but adding:

```haxe
case SfClosureField(inst, field):
    printf(r, field.parentClass + "_" + field.classField.name);
```

to SfGenerator.hx, however, this also means you end up with code something like:

```
this[@3]=test_myTestFn3;
script_execute(this[3]);
```

Which is fine until you try to access a member var from said class as, i think, it should be something more like:

```
this[@3]=test_myTestFn3;
script_execute(this[3], this);
```

There is a `callNeedsThis` on `SfClassField` which looking at the generator seems to be exactly what is needed, however, i couldnt get it to work (or set) correctly - not _really_ knowing the details of the generator 

Cheers,
Ian

**Comment by YellowAfterlife** [comment]
I'm waiting for GML 2.3 update, which is to introduce ability to bind context to a script, not unlike the 1-argument version of JS/ES `Function.bind`.

In the current form, allowing closures would mean having to check and unpack a context-script pair whenever a function is to be called, in contrast to using GameMaker's unreasonably fast reflection-call (`script_execute`) directly.

At this time you could do this
```
class Some {
   public var name:String;
   private var _testFn:(self:Some, text:String)->Void;
   
   public function new() {
       _testFn = function(self, text) trace('${self.name}: $text');
   }
```

**Comment by ianharrigan** [comment]
OK, great - thanks for the response. Ill probably just have a look at this again when GML 2.3 comes, and of course, you've had time to work your magic. 

Thanks again,
Ian
